INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Picadilly', 'P1', '1Q');

INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, ADDRESS, COUNTRY, STATE, PHONE_NUMBER) VALUES ('Khizar', 'Malik', 'Kmalik1122@gmail.com', 'London', 'United Kingdom', 'London', '7494883834');

INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES (1, 1, '2019-02-02');
